
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import teletubies.database.DatabaseHandler;
import teletubies.model.EmployeeDB;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Hall_PC
 */
public class EmployeePanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportEmpPanel
     */
    public EmployeePanel() {
        initComponents();
        empGen();

    }

    //Show employee on gui
    public void empGen() {
        DefaultTableModel tableModel = (DefaultTableModel) showEmpTable.getModel();
        tableModel.setRowCount(0);
        try {
            ArrayList<EmployeeDB> employeeDBs = DatabaseHandler.findAllEmployee(new DatabaseHandler());
            for (int i = 0; i < employeeDBs.size(); i++) {
                tableModel.addRow(new Object[]{employeeDBs.get(i).getEmployeeID(),
                    employeeDBs.get(i).getFirstName(),
                    employeeDBs.get(i).getLastName(),
                    employeeDBs.get(i).getPhoneNumber(),
                    employeeDBs.get(i).getAddress(),
                    employeeDBs.get(i).getEmployeeLevel()});
            }
        } catch (Exception e) {
            System.err.println("Error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        insertEmpPanel = new javax.swing.JPanel();
        textEmp = new javax.swing.JLabel();
        inputEmpBox = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        firstNameText = new javax.swing.JLabel();
        inputFirstNameBox = new javax.swing.JTextField();
        lastNameText = new javax.swing.JLabel();
        inputLastnameBox = new javax.swing.JTextField();
        passwordText = new javax.swing.JLabel();
        inputPasswordBox = new javax.swing.JTextField();
        ageText = new javax.swing.JLabel();
        inputAgeBox = new javax.swing.JTextField();
        addressText = new javax.swing.JLabel();
        inputAddressBox = new javax.swing.JTextField();
        workText = new javax.swing.JLabel();
        InputWork = new javax.swing.JTextField();
        LevelText = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        Phone = new javax.swing.JLabel();
        InputPhoneBox = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        removeEmpPanel = new javax.swing.JPanel();
        removeEmpText = new javax.swing.JLabel();
        inputRemoveEmpBox = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        RemoveTitle = new javax.swing.JLabel();
        cookingTableScrollPane = new javax.swing.JScrollPane();
        showEmpTable = new javax.swing.JTable();

        setLayout(null);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Title.setText("Manage Employee");
        add(Title);
        Title.setBounds(130, 10, 420, 80);

        insertEmpPanel.setBackground(new java.awt.Color(204, 204, 204));
        insertEmpPanel.setLayout(null);

        textEmp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textEmp.setText("Employee ID");
        insertEmpPanel.add(textEmp);
        textEmp.setBounds(20, 50, 120, 30);

        inputEmpBox.setForeground(new java.awt.Color(153, 153, 153));
        inputEmpBox.setText("0001");
        inputEmpBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputEmpBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputEmpBoxMouseClicked(evt);
            }
        });
        inputEmpBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputEmpBoxKeyTyped(evt);
            }
        });
        insertEmpPanel.add(inputEmpBox);
        inputEmpBox.setBounds(20, 90, 270, 40);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 255));
        title.setText("Register Employee");
        insertEmpPanel.add(title);
        title.setBounds(210, 10, 220, 40);

        firstNameText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstNameText.setText("FirstName");
        insertEmpPanel.add(firstNameText);
        firstNameText.setBounds(20, 130, 120, 30);

        inputFirstNameBox.setForeground(new java.awt.Color(153, 153, 153));
        inputFirstNameBox.setText("John");
        inputFirstNameBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputFirstNameBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputFirstNameBoxMouseClicked(evt);
            }
        });
        inputFirstNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFirstNameBoxActionPerformed(evt);
            }
        });
        insertEmpPanel.add(inputFirstNameBox);
        inputFirstNameBox.setBounds(20, 170, 270, 40);

        lastNameText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lastNameText.setText("LastName");
        insertEmpPanel.add(lastNameText);
        lastNameText.setBounds(320, 130, 120, 30);

        inputLastnameBox.setForeground(new java.awt.Color(153, 153, 153));
        inputLastnameBox.setText("Good");
        inputLastnameBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputLastnameBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputLastnameBoxMouseClicked(evt);
            }
        });
        inputLastnameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLastnameBoxActionPerformed(evt);
            }
        });
        insertEmpPanel.add(inputLastnameBox);
        inputLastnameBox.setBounds(320, 170, 270, 40);

        passwordText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        passwordText.setText("password");
        insertEmpPanel.add(passwordText);
        passwordText.setBounds(20, 210, 120, 30);

        inputPasswordBox.setForeground(new java.awt.Color(153, 153, 153));
        inputPasswordBox.setText("John123456");
        inputPasswordBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputPasswordBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputPasswordBoxMouseClicked(evt);
            }
        });
        inputPasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordBoxActionPerformed(evt);
            }
        });
        inputPasswordBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPasswordBoxKeyTyped(evt);
            }
        });
        insertEmpPanel.add(inputPasswordBox);
        inputPasswordBox.setBounds(20, 250, 270, 40);

        ageText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ageText.setText("Age");
        insertEmpPanel.add(ageText);
        ageText.setBounds(20, 300, 120, 30);

        inputAgeBox.setForeground(new java.awt.Color(153, 153, 153));
        inputAgeBox.setText("18");
        inputAgeBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAgeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputAgeBoxMouseClicked(evt);
            }
        });
        inputAgeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAgeBoxActionPerformed(evt);
            }
        });
        inputAgeBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputAgeBoxKeyTyped(evt);
            }
        });
        insertEmpPanel.add(inputAgeBox);
        inputAgeBox.setBounds(20, 340, 270, 40);

        addressText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addressText.setText("Address");
        insertEmpPanel.add(addressText);
        addressText.setBounds(320, 300, 120, 30);

        inputAddressBox.setForeground(new java.awt.Color(153, 153, 153));
        inputAddressBox.setText("bangkok 101/40");
        inputAddressBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputAddressBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputAddressBoxMouseClicked(evt);
            }
        });
        inputAddressBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAddressBoxActionPerformed(evt);
            }
        });
        insertEmpPanel.add(inputAddressBox);
        inputAddressBox.setBounds(320, 340, 270, 40);

        workText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        workText.setText("WorkStatus");
        insertEmpPanel.add(workText);
        workText.setBounds(20, 390, 190, 30);

        InputWork.setEditable(false);
        InputWork.setText("work");
        InputWork.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputWorkMouseClicked(evt);
            }
        });
        InputWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputWorkActionPerformed(evt);
            }
        });
        insertEmpPanel.add(InputWork);
        InputWork.setBounds(20, 430, 270, 40);

        LevelText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LevelText.setText("Level of Work");
        insertEmpPanel.add(LevelText);
        LevelText.setBounds(320, 390, 200, 30);

        addButton.setBackground(new java.awt.Color(0, 102, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        insertEmpPanel.add(addButton);
        addButton.setBounds(450, 490, 145, 46);

        Phone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Phone.setText("Phone Number");
        Phone.setToolTipText("");
        insertEmpPanel.add(Phone);
        Phone.setBounds(320, 210, 120, 30);

        InputPhoneBox.setForeground(new java.awt.Color(153, 153, 153));
        InputPhoneBox.setText("0123456789");
        InputPhoneBox.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        InputPhoneBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputPhoneBoxMouseClicked(evt);
            }
        });
        InputPhoneBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPhoneBoxKeyTyped(evt);
            }
        });
        insertEmpPanel.add(InputPhoneBox);
        InputPhoneBox.setBounds(320, 250, 270, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cashier", "Cook" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        insertEmpPanel.add(jComboBox1);
        jComboBox1.setBounds(320, 430, 270, 40);

        add(insertEmpPanel);
        insertEmpPanel.setBounds(620, 10, 620, 560);

        removeEmpPanel.setBackground(new java.awt.Color(204, 204, 204));
        removeEmpPanel.setLayout(null);

        removeEmpText.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        removeEmpText.setText("Employee Name");
        removeEmpPanel.add(removeEmpText);
        removeEmpText.setBounds(250, 10, 130, 30);

        inputRemoveEmpBox.setForeground(new java.awt.Color(153, 153, 153));
        inputRemoveEmpBox.setText("Mart Jordan");
        inputRemoveEmpBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputRemoveEmpBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputRemoveEmpBoxMouseClicked(evt);
            }
        });
        inputRemoveEmpBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRemoveEmpBoxActionPerformed(evt);
            }
        });
        inputRemoveEmpBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputRemoveEmpBoxKeyTyped(evt);
            }
        });
        removeEmpPanel.add(inputRemoveEmpBox);
        inputRemoveEmpBox.setBounds(250, 40, 170, 50);

        removeButton.setBackground(new java.awt.Color(255, 0, 0));
        removeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("REMOVE");
        removeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        removeEmpPanel.add(removeButton);
        removeButton.setBounds(450, 40, 145, 46);

        RemoveTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RemoveTitle.setForeground(new java.awt.Color(255, 0, 0));
        RemoveTitle.setText("Remove Employee");
        removeEmpPanel.add(RemoveTitle);
        RemoveTitle.setBounds(20, 40, 220, 40);

        add(removeEmpPanel);
        removeEmpPanel.setBounds(620, 580, 620, 120);

        showEmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeID", "FirstName", "LastName", "PhoneNumber", "Address", "EmployeeLevel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showEmpTable.setAlignmentX(-10.0F);
        showEmpTable.setGridColor(new java.awt.Color(0, 102, 255));
        showEmpTable.setRowHeight(40);
        showEmpTable.setRowMargin(5);
        cookingTableScrollPane.setViewportView(showEmpTable);

        add(cookingTableScrollPane);
        cookingTableScrollPane.setBounds(20, 110, 590, 590);
    }// </editor-fold>//GEN-END:initComponents

    //press button to add employee to database and refresh data on gui
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try {
            EmployeeDB emp = new EmployeeDB();
            boolean isClickedAll = clicked[0] && clicked[1] && clicked[2] && clicked[3] && clicked[4] && clicked[5] && clicked[6];
            String empid = inputEmpBox.getText();
            String fname = inputFirstNameBox.getText();
            String lname = inputLastnameBox.getText();
            String pass = inputPasswordBox.getText();
            String age = inputAgeBox.getText();
            String address = inputAddressBox.getText();
            String phonenumber = InputPhoneBox.getText();
            if (!isClickedAll){
                JOptionPane.showMessageDialog(null, "Please Enter All Data", "Error", JOptionPane.WARNING_MESSAGE);
            }
            else if ((DatabaseHandler.findEmployeeById(new DatabaseHandler(), Integer.parseInt(empid)) == null) && (!empid.equals("")) && (!fname.equals("")) && (!lname.equals("")) && (!pass.equals("")) && (!age.equals("")) && (!address.equals("")) && (!phonenumber.equals("")) && ((jComboBox1.getSelectedIndex()+1) != 3)) {
                emp.setEmployeeID(Integer.parseInt(empid));
                emp.setFirstName(fname);
                emp.setLastName(lname);
                emp.setPasswordEmp(pass);
                emp.setAge(Integer.parseInt(age));
                emp.setAddress(address);
                emp.setPhoneNumber(phonenumber);
                emp.setWorkStatus(InputWork.getText());
                emp.setEmployeeLevel(jComboBox1.getSelectedIndex()+1);
                DatabaseHandler.insertEmployee(new DatabaseHandler(), emp);
                empGen();
            } 
            else if ((DatabaseHandler.findEmployeeById(new DatabaseHandler(), Integer.parseInt(empid)) == null) && (!empid.equals("")) && (!fname.equals("")) && (!lname.equals("")) && (!pass.equals("")) && (!age.equals("")) && (!address.equals("")) && (!phonenumber.equals("")) && ((jComboBox1.getSelectedIndex()+1) == 3) ) {
                JOptionPane.showMessageDialog(null, "Cant Register Manager", "Error", JOptionPane.WARNING_MESSAGE);
            }
            else if((empid.equals("")) || (fname.equals("")) || (lname.equals("")) || (pass.equals("")) || (age.equals("")) || (address.equals("")) || (phonenumber.equals("")) ){
                JOptionPane.showMessageDialog(null, "Please Enter All Enter", "Error", JOptionPane.WARNING_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "ID Already Exist", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.WARNING_MESSAGE);
        }
        inputEmpBox.setText("");
        inputFirstNameBox.setText("");
        inputLastnameBox.setText("");
        InputPhoneBox.setText("");
        inputAddressBox.setText("");
        inputAgeBox.setText("");
        inputPasswordBox.setText("");
        
        inputRemoveEmpBox.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void inputRemoveEmpBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRemoveEmpBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRemoveEmpBoxActionPerformed

    //press button to remove employee to database and refresh data on gui
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        try {
                String Fullname = inputRemoveEmpBox.getText();
                String[] Name = Fullname.split(" ", 2);
                EmployeeDB emp = DatabaseHandler.findEmployeeByFullName(new DatabaseHandler(), Name[0], Name[1]);
                if (emp.getEmployeeLevel() < 3)
                {
                DatabaseHandler.removeEmployee(new DatabaseHandler(), emp);
                } else {
                    JOptionPane.showMessageDialog(null, "Can't Delete Manager", "Error", JOptionPane.WARNING_MESSAGE);
                }
                empGen();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        inputEmpBox.setText("");
        inputFirstNameBox.setText("");
        inputLastnameBox.setText("");
        InputPhoneBox.setText("");
        inputAddressBox.setText("");
        inputAgeBox.setText("");
        inputPasswordBox.setText("");
        
        inputRemoveEmpBox.setText("");
    }//GEN-LAST:event_removeButtonActionPerformed

    private void inputLastnameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLastnameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLastnameBoxActionPerformed

    private void inputPasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordBoxActionPerformed

    private void inputAgeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAgeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAgeBoxActionPerformed

    private void inputAddressBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAddressBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAddressBoxActionPerformed

    private void InputWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputWorkActionPerformed

    private void inputAgeBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputAgeBoxMouseClicked
        // TODO add your handling code here:
        clicked[5] = true;
        inputAgeBox.setText("");
        inputAgeBox.setEditable(true);
        inputAgeBox.setForeground(Color.black);
    }//GEN-LAST:event_inputAgeBoxMouseClicked

    private void inputEmpBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputEmpBoxMouseClicked
        // TODO add your handling code here:
        clicked[0] = true;
        inputEmpBox.setText("");
        inputEmpBox.setEditable(true);
        inputEmpBox.setForeground(Color.black);
    }//GEN-LAST:event_inputEmpBoxMouseClicked

    private void inputFirstNameBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputFirstNameBoxMouseClicked
        // TODO add your handling code here:
        clicked[1] = true;
        inputFirstNameBox.setText("");
        inputFirstNameBox.setEditable(true);
        inputFirstNameBox.setForeground(Color.black);
    }//GEN-LAST:event_inputFirstNameBoxMouseClicked

    private void inputLastnameBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputLastnameBoxMouseClicked
        // TODO add your handling code here:
        clicked[2] = true;
        inputLastnameBox.setText("");
        inputLastnameBox.setEditable(true);
        inputLastnameBox.setForeground(Color.black);
    }//GEN-LAST:event_inputLastnameBoxMouseClicked

    private void inputPasswordBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordBoxMouseClicked
        // TODO add your handling code here:
        clicked[3] = true;
        inputPasswordBox.setText("");
        inputPasswordBox.setEditable(true);
        inputPasswordBox.setForeground(Color.black);
    }//GEN-LAST:event_inputPasswordBoxMouseClicked

    private void inputAddressBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputAddressBoxMouseClicked
        // TODO add your handling code here:
        clicked[6] = true;
        inputAddressBox.setText("");
        inputAddressBox.setEditable(true);
        inputAddressBox.setForeground(Color.black);
    }//GEN-LAST:event_inputAddressBoxMouseClicked

    private void InputWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputWorkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InputWorkMouseClicked

    private void inputRemoveEmpBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputRemoveEmpBoxMouseClicked
        // TODO add your handling code here:
        inputRemoveEmpBox.setText("");
        inputRemoveEmpBox.setEditable(true);
        inputRemoveEmpBox.setForeground(Color.black);
    }//GEN-LAST:event_inputRemoveEmpBoxMouseClicked

    private void InputPhoneBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputPhoneBoxMouseClicked
        // TODO add your handling code here:
        clicked[4] = true;
        InputPhoneBox.setText("");
        InputPhoneBox.setEditable(true);
        InputPhoneBox.setForeground(Color.black);
    }//GEN-LAST:event_InputPhoneBoxMouseClicked

    private void inputFirstNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFirstNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFirstNameBoxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void inputEmpBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputEmpBoxKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_inputEmpBoxKeyTyped

    private void inputAgeBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAgeBoxKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_inputAgeBoxKeyTyped

    private void InputPhoneBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPhoneBoxKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_InputPhoneBoxKeyTyped

    private void inputPasswordBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPasswordBoxKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            JOptionPane.showMessageDialog(null, "You can't enter alphabets here", "Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_inputPasswordBoxKeyTyped

    private void inputRemoveEmpBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputRemoveEmpBoxKeyTyped

    }//GEN-LAST:event_inputRemoveEmpBoxKeyTyped

    private boolean[] clicked = {false,false,false,false,false,false,false,false};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputPhoneBox;
    private javax.swing.JTextField InputWork;
    private javax.swing.JLabel LevelText;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel RemoveTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressText;
    private javax.swing.JLabel ageText;
    private javax.swing.JScrollPane cookingTableScrollPane;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JTextField inputAddressBox;
    private javax.swing.JTextField inputAgeBox;
    private javax.swing.JTextField inputEmpBox;
    private javax.swing.JTextField inputFirstNameBox;
    private javax.swing.JTextField inputLastnameBox;
    private javax.swing.JTextField inputPasswordBox;
    private javax.swing.JTextField inputRemoveEmpBox;
    private javax.swing.JPanel insertEmpPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JLabel passwordText;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel removeEmpPanel;
    private javax.swing.JLabel removeEmpText;
    private javax.swing.JTable showEmpTable;
    private javax.swing.JLabel textEmp;
    private javax.swing.JLabel title;
    private javax.swing.JLabel workText;
    // End of variables declaration//GEN-END:variables
}
