
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import teletubies.database.DatabaseHandler;
import teletubies.model.ReportSellDaliy;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Hall_PC
 */
public class ReportSaledaily extends javax.swing.JPanel {

    /**
     * Creates new form ReportEmpPanel
     */
    public ReportSaledaily() {
        initComponents();
        reportGen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cookingTableScrollPane = new javax.swing.JScrollPane();
        reportSaleDailyTable = new javax.swing.JTable();
        reportSaleDailyTitleLabel = new javax.swing.JLabel();
        printReportSaleDailyButton = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sumValue = new javax.swing.JLabel();

        setLayout(null);

        reportSaleDailyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Emp ID", "FoodName", "Price", "Quatity", "totalPrice", "Sale TimeStamp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportSaleDailyTable.setAlignmentX(-10.0F);
        reportSaleDailyTable.setGridColor(new java.awt.Color(0, 102, 255));
        reportSaleDailyTable.setRowHeight(40);
        reportSaleDailyTable.setRowMargin(5);
        cookingTableScrollPane.setViewportView(reportSaleDailyTable);

        add(cookingTableScrollPane);
        cookingTableScrollPane.setBounds(40, 110, 1180, 520);

        reportSaleDailyTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        reportSaleDailyTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportSaleDailyTitleLabel.setText("Report Sale Daily (02 Jan 2020)");
        add(reportSaleDailyTitleLabel);
        reportSaleDailyTitleLabel.setBounds(310, 20, 740, 70);

        printReportSaleDailyButton.setBackground(new java.awt.Color(204, 204, 204));
        printReportSaleDailyButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        printReportSaleDailyButton.setText("Print");
        printReportSaleDailyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReportSaleDailyButtonActionPerformed(evt);
            }
        });
        add(printReportSaleDailyButton);
        printReportSaleDailyButton.setBounds(1050, 40, 170, 50);

        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });
        add(searchBar);
        searchBar.setBounds(50, 70, 290, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Total Sale :");
        add(jLabel1);
        jLabel1.setBounds(40, 630, 190, 40);

        sumValue.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        sumValue.setText("0.0 Bath");
        add(sumValue);
        sumValue.setBounds(230, 630, 370, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void printReportSaleDailyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReportSaleDailyButtonActionPerformed
        String path = "./Report";
        
        Date date = new Date();
        SimpleDateFormat format= new SimpleDateFormat("yyyy_MM_dd_hh_mm_ss",Locale.ENGLISH);
        SimpleDateFormat reportformat= new SimpleDateFormat("dd/MM/yyyy hh:mm:ss aa",Locale.ENGLISH);
        
        String filepath = path + "/"+"ReportSaleDaily"+format.format(date) + ".pdf";
        
        String dochead = "Report Sale Daily (" + reportformat.format(date) + ")";
        String sum = sumValue.getText();
        
        Document doc = new Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(filepath) );
            doc.open();
            
            Paragraph head = new Paragraph(dochead,FontFactory.getFont(FontFactory.TIMES_ROMAN,30, Font.BOLD, BaseColor.BLACK));
            head.setAlignment(Paragraph.ALIGN_CENTER);
            doc.add(head);
            
            doc.add(new Paragraph("\n"));
            
            Paragraph s = new Paragraph("Total Sale : " + sum);
            s.setAlignment(Paragraph.ALIGN_CENTER);
            doc.add(s);
            
            doc.add(new Paragraph("\n"));
            
            PdfPTable tbl = new PdfPTable(7);

            //add header
            tbl.addCell("OrderID");
            tbl.addCell("EmployeeID");
            tbl.addCell("FoodName");
            tbl.addCell("FoodPrice");
            tbl.addCell("Quatity");
            tbl.addCell("Total Price");
            tbl.addCell("Sale Timestamp");

            for(int i = 0 ; i < reportSaleDailyTable.getRowCount() ; i++){
                String orderid = reportSaleDailyTable.getValueAt(i,0).toString();
                String empid = reportSaleDailyTable.getValueAt(i,1).toString();
                String foodname = reportSaleDailyTable.getValueAt(i,2).toString();
                String price = reportSaleDailyTable.getValueAt(i,3).toString();
                String quantity = reportSaleDailyTable.getValueAt(i,4).toString();
                String totalprice = reportSaleDailyTable.getValueAt(i,5).toString();
                String saletimestamp = reportSaleDailyTable.getValueAt(i,6).toString();

                tbl.addCell(orderid);
                tbl.addCell(empid);
                tbl.addCell(foodname);
                tbl.addCell(price);
                tbl.addCell(quantity);
                tbl.addCell(totalprice);
                tbl.addCell(saletimestamp);

            }
            doc.add(tbl);
            JOptionPane.showMessageDialog(null , "Print Report Sale Daily Success" , "ALERT MESSAGE" , JOptionPane.INFORMATION_MESSAGE);

        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(ReportSale.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(DocumentException ex){
            Logger.getLogger(ReportSale.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
        
        openReport(filepath);
    }//GEN-LAST:event_printReportSaleDailyButtonActionPerformed
    
    public void openReport(String path){
        try{
            File file = new File(path);
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(null , "Not Supported" , "ALERT MESSAGE" , JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null , "No Bill Exist" , "ALERT MESSAGE" , JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);      
        String time = formatter.format(date);
        String search = searchBar.getText();
        DefaultTableModel empModel = (DefaultTableModel) reportSaleDailyTable.getModel();
        empModel.setNumRows(0);
        if(!search.equals("") ){
            try {
                ArrayList<ReportSellDaliy> ReportOrderDBs = DatabaseHandler.findReportSaleDaliyOrderById(new DatabaseHandler(), Integer.parseInt(search), time);
                int length = ReportOrderDBs.size();
                //sum = 0;

                if (length > 0) {
                    for (int i = 0; i < length; i++) {
                        empModel.addRow(new Object[]{ReportOrderDBs.get(i).getOrderID(),
                        ReportOrderDBs.get(i).getEmployeeID(),
                        ReportOrderDBs.get(i).getFoodName(),
                        ReportOrderDBs.get(i).getFoodPrice(),
                        ReportOrderDBs.get(i).getQuantity(),
                        ReportOrderDBs.get(i).getTotalPrice(),
                        ReportOrderDBs.get(i).getSaleTimestamp()});
                        //sum += ReportOrderDBs.get(i).getFoodPrice();

                    }
                    //sumValue.setText(String.valueOf(sum)+" Bath");
                }
            } 
            catch (Exception e) {
                System.err.println(e);
                //sumValue.setText("0.0 Bath");
            }
        }
        else if(search.equals("")){
            reportGen();
        }
    }//GEN-LAST:event_searchBarKeyReleased

    //Show report sale daily on gui
    private void reportGen() {
        try {
            Date nowDate = new Date();//For reference
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            String formattedString = formatter.format(nowDate);
            reportSaleDailyTitleLabel.setText("Report Sale Daily (" + formattedString + ")");
            DefaultTableModel tableModel = (DefaultTableModel) reportSaleDailyTable.getModel();
            ArrayList<ReportSellDaliy> orderDailyTable = DatabaseHandler.findReportOrderByTime(new DatabaseHandler(), formattedString);
            int length = orderDailyTable.size();
            sum = 0;
            if (length > 0) {
                for (int i = 0; i < length; i++) {
                    tableModel.addRow(new Object[]{orderDailyTable.get(i).getOrderID(),
                        orderDailyTable.get(i).getEmployeeID(),
                        orderDailyTable.get(i).getFoodName(),
                        orderDailyTable.get(i).getFoodPrice(),
                        orderDailyTable.get(i).getQuantity(),
                        orderDailyTable.get(i).getTotalPrice(),
                        orderDailyTable.get(i).getSaleTimestamp()});
                        sum += orderDailyTable.get(i).getFoodPrice();
                }
                sumValue.setText(String.valueOf(sum)+" Bath");
            }
        } catch (Exception ex) {
            System.out.println("No order yet.");;
        }
    }

    private double sum = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane cookingTableScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton printReportSaleDailyButton;
    private javax.swing.JTable reportSaleDailyTable;
    private javax.swing.JLabel reportSaleDailyTitleLabel;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel sumValue;
    // End of variables declaration//GEN-END:variables
}
